
import { Region } from "./types";

export const COLORS = {
    NEON_PINK: '#ec4899',
    WHITE: '#FFFFFF',
    BG_DARK: '#000000',
    SPRINKLE_PALETTE: ['#ec4899', '#FFFFFF', '#AAAAAA', '#666666', '#333333']
};

export const RISK_REGIONS: Region[] = [
    { id: 'NA1', name: 'Alaska', lat: 64, lon: -150 },
    { id: 'NA2', name: 'Yukon', lat: 65, lon: -135 },
    { id: 'NA3', name: 'Nunavut', lat: 70, lon: -95 },
    { id: 'NA4', name: 'Greenland', lat: 72, lon: -40 },
    { id: 'NA5', name: 'Cascadia', lat: 50, lon: -122 },
    { id: 'NA6', name: 'Alberta', lat: 55, lon: -115 },
    { id: 'NA7', name: 'Manitoba', lat: 55, lon: -98 },
    { id: 'NA8', name: 'Ontario', lat: 52, lon: -85 },
    { id: 'NA9', name: 'Quebec', lat: 53, lon: -70 },
    { id: 'NA10', name: 'Maritimes', lat: 46, lon: -63 },
    { id: 'NA11', name: 'California', lat: 37, lon: -120 },
    { id: 'NA12', name: 'Great Basin', lat: 40, lon: -112 },
    { id: 'NA13', name: 'Heartland', lat: 40, lon: -92 },
    { id: 'NA14', name: 'Dixie', lat: 33, lon: -88 },
    { id: 'NA15', name: 'New England', lat: 42, lon: -75 },
    { id: 'NA16', name: 'Mexico', lat: 24, lon: -102 },
    { id: 'NA17', name: 'Caribbean', lat: 18, lon: -75 },
    { id: 'SA1', name: 'Gran Colombia', lat: 5, lon: -74 },
    { id: 'SA2', name: 'Amazonas', lat: -3, lon: -60 },
    { id: 'SA3', name: 'Guiana', lat: 5, lon: -55 },
    { id: 'SA4', name: 'Andes', lat: -10, lon: -76 },
    { id: 'SA5', name: 'Altiplano', lat: -17, lon: -65 },
    { id: 'SA6', name: 'Mato Grosso', lat: -15, lon: -55 },
    { id: 'SA7', name: 'Sertão', lat: -10, lon: -40 },
    { id: 'SA8', name: 'Pampas', lat: -34, lon: -60 },
    { id: 'SA9', name: 'Patagonia', lat: -45, lon: -70 },
    { id: 'SA10', name: 'Tierra del Fuego', lat: -54, lon: -68 },
    { id: 'EU1', name: 'Iceland', lat: 65, lon: -18 },
    { id: 'EU2', name: 'Hibernia', lat: 53, lon: -8 },
    { id: 'EU3', name: 'Albion', lat: 54, lon: -2 },
    { id: 'EU4', name: 'Scandinavia', lat: 62, lon: 10 },
    { id: 'EU5', name: 'Lapland', lat: 68, lon: 25 },
    { id: 'EU6', name: 'Iberia', lat: 40, lon: -4 },
    { id: 'EU7', name: 'Gaul', lat: 47, lon: 2 },
    { id: 'EU8', name: 'Rhine', lat: 51, lon: 9 },
    { id: 'EU9', name: 'Italia', lat: 42, lon: 13 },
    { id: 'EU10', name: 'Polonia', lat: 52, lon: 20 },
    { id: 'EU11', name: 'Danubia', lat: 47, lon: 18 },
    { id: 'EU12', name: 'Balkans', lat: 42, lon: 22 },
    { id: 'EU13', name: 'Baltica', lat: 57, lon: 26 },
    { id: 'EU14', name: 'Muscovy', lat: 56, lon: 37 },
    { id: 'EU15', name: 'Crimea', lat: 46, lon: 34 },
    { id: 'AF1', name: 'Maghreb', lat: 32, lon: 0 },
    { id: 'AF2', name: 'Tripolitania', lat: 28, lon: 15 },
    { id: 'AF3', name: 'Aegyptus', lat: 27, lon: 30 },
    { id: 'AF4', name: 'Sahara', lat: 20, lon: 0 },
    { id: 'AF5', name: 'Sahel', lat: 15, lon: 15 },
    { id: 'AF6', name: 'Nubia', lat: 15, lon: 32 },
    { id: 'AF7', name: 'Abyssinia', lat: 8, lon: 38 },
    { id: 'AF8', name: 'Gold Coast', lat: 8, lon: -5 },
    { id: 'AF9', name: 'Kongo', lat: -2, lon: 22 },
    { id: 'AF10', name: 'Tanganyika', lat: -6, lon: 35 },
    { id: 'AF11', name: 'Angola', lat: -12, lon: 18 },
    { id: 'AF12', name: 'Zambezia', lat: -18, lon: 30 },
    { id: 'AF13', name: 'Kalahari', lat: -24, lon: 22 },
    { id: 'AF14', name: 'Cape', lat: -30, lon: 24 },
    { id: 'AS1', name: 'Anatolia', lat: 39, lon: 35 },
    { id: 'AS2', name: 'Levant', lat: 33, lon: 37 },
    { id: 'AS3', name: 'Arabia', lat: 24, lon: 45 },
    { id: 'AS4', name: 'Mesopotamia', lat: 33, lon: 44 },
    { id: 'AS5', name: 'Persia', lat: 32, lon: 53 },
    { id: 'AS6', name: 'Turkestan', lat: 42, lon: 65 },
    { id: 'AS7', name: 'Pamir', lat: 38, lon: 70 },
    { id: 'AS8', name: 'Indus', lat: 28, lon: 70 },
    { id: 'AS9', name: 'Hindustan', lat: 22, lon: 78 },
    { id: 'AS10', name: 'Bengal', lat: 24, lon: 90 },
    { id: 'AS11', name: 'Deccan', lat: 15, lon: 78 },
    { id: 'AS12', name: 'Tibet', lat: 32, lon: 88 },
    { id: 'AS13', name: 'Xian', lat: 40, lon: 90 },
    { id: 'AS14', name: 'Cathay', lat: 36, lon: 110 },
    { id: 'AS15', name: 'Manchuria', lat: 45, lon: 125 },
    { id: 'AS16', name: 'Gobi', lat: 46, lon: 105 },
    { id: 'AS17', name: 'Siberia West', lat: 60, lon: 75 },
    { id: 'AS18', name: 'Siberia Central', lat: 62, lon: 100 },
    { id: 'AS19', name: 'Siberia East', lat: 64, lon: 130 },
    { id: 'AS20', name: 'Kamchatka', lat: 58, lon: 160 },
    { id: 'AS21', name: 'Amur', lat: 50, lon: 135 },
    { id: 'AS22', name: 'Korea', lat: 38, lon: 127 },
    { id: 'AS23', name: 'Japan', lat: 36, lon: 138 },
    { id: 'AS24', name: 'Indochina', lat: 18, lon: 105 },
    { id: 'AS25', name: 'Malaya', lat: 5, lon: 102 },
    { id: 'AU1', name: 'Nusantara', lat: -2, lon: 115 },
    { id: 'AU2', name: 'Philippines', lat: 13, lon: 122 },
    { id: 'AU3', name: 'Papua', lat: -5, lon: 140 },
    { id: 'AU4', name: 'Pilbara', lat: -24, lon: 120 },
    { id: 'AU5', name: 'Outback', lat: -25, lon: 133 },
    { id: 'AU6', name: 'Queensland', lat: -22, lon: 145 },
    { id: 'AU7', name: 'New South Wales', lat: -32, lon: 147 },
    { id: 'AU8', name: 'Zealandia', lat: -42, lon: 172 }
];
